### ISSUE TITLE
Batch feed transactions to minimise “Gas fee”

### ISSUE THREAD

**Issue by ParhaMDeF** [xclud/web3dart#105]
Superbatching can be an effective method for lowering gas fees by combining multiple transactions into one, which reduces the overall gas cost.

**Comment by xclud** [comment]
> In early 2021, a new Ethereum Improvement Protocol (EIP) proposal was adopted by the Ethereum blockchain known as EIP-3074 that was set to be implemented in July of the same year.
> 
> The proposal was put forward in October 2020 and gained substantial backing. While this proposal wasn't solely designed to lower gas fees through batch transactions, it did open the door to users who wanted to achieve this perk. [Ethereum stated](https://eips.ethereum.org/EIPS/eip-3074) that EIP-3074 came as a result of users making requests for "implementing batching capabilities, allowing for gas sponsoring, expirations, scripting, and beyond."

Source: https://www.makeuseof.com/how-batch-ethereum-transactions-cheaper-gas-fees/

**Comment by xclud** [comment]
https://eips.ethereum.org/EIPS/eip-3074
