### ISSUE TITLE
Need to Update Version http ^0.13.x to http ^1.x.x [Latest Version]

### ISSUE THREAD

**Issue by ttb-inc** [xclud/web3dart#111]
Because web3dart >=2.5.2 depends on http ^0.13.5 and every version of ttb_core from path depends on http 1.1.0, web3dart >=2.5.2 is incompatible with ttb_core from path.
So, because ttb_wallet depends on both ttb_core from path and web3dart 2.6.1, version solving failed.

Thank you.

**Comment by xclud** [comment]
Thanks for reporting.

Fixed in `2.7.0`.
