### ISSUE TITLE
How to manage revert instruction

### ISSUE THREAD

**Issue by redDwarf03** [xclud/web3dart#118]
I would like to catch revert keywords in smart contract
Is it possible with your lib ?
thx

**Comment by makinghappen** [comment]
@redDwarf03 it is not supported, I would like to have it as well, so future plans would include this, if you would also like to make a contribution- it is very welcome!

**Comment by redDwarf03** [comment]
I don’t know how to do that 😅

**Comment by redDwarf03** [comment]
do you know if something like interface.parseError in ether.js exists in dart ? Thx

**Comment by redDwarf03** [comment]
The best way to get revert or error type from solidity is to use https://pub.dev/packages/wagmi_flutter_web
