### ISSUE TITLE
503 Service Temporarily Unavailable Error on sendTransaction method

### ISSUE THREAD

**Issue by msalman2890** [xclud/web3dart#119]
Unable to perform transactions due to the server issue. Please take a look.

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by xclud** [comment]
This is an internal server error. Not a problem with web3dart. Closing.

**Comment by msalman2890** [comment]
What is the reason behind it? Why server is throwing error?

**Comment by msalman2890** [comment]
This error is throwing from sendTransaction method

**Comment by xclud** [comment]
Please contact your server administrator.
