### ISSUE TITLE
How to call secp256K1 directly, the private key package is hashed using keccak256

### ISSUE THREAD

**Issue by querli** [xclud/web3dart#138]
<img width="864" alt="image" src="https://github.com/xclud/web3dart/assets/45426897/2988e110-9f27-4212-91ba-c1c0aa847cf0">
<img width="646" alt="image" src="https://github.com/xclud/web3dart/assets/45426897/702d382a-9e70-4790-b300-489fa8d6c2f7">
How can I directly reference the secp256k1.dart file？

**Comment by xclud** [comment]
I hope this helps: https://pub.dev/packages/sec

**Comment by querli** [comment]
> I hope this helps: https://pub.dev/packages/sec

Thank you very much
