### ISSUE TITLE
Metamask error after transaction.callContract

### ISSUE THREAD

**Issue by Jens05** [xclud/web3dart#26]
Hi, when i make a transaction with my contractabi everything works perfectly. I managed to obtain credentials etc. When i open metamask and accept the incoming transactions everything is okay, but 5 seconds later i get the message: oops! Something went wrong! :/. When i tap on the error it opens an empty popup with no information. Thanks in advance!

**Comment by Aziiz777** [comment]
Hi @Jens05 
Can you help me in "manage to obtain credentials"?

**Comment by Jens05** [comment]
Of course, pls dm me on discord or twitter.

**Comment by Jens05** [comment]
Jens#7810

**Comment by DONOVAN7493** [comment]
HI @nik-suri I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#

**Comment by DONOVAN7493** [comment]
HI @Jens05 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#

**Comment by Jens05** [comment]
Turns out it is a metamask-related issue

**Comment by LongTien15** [comment]
can you show the code obtain credentials from metamask please? I'm stuck there
