### ISSUE TITLE
Package compatibility issues. (Not bug)

### ISSUE THREAD

**Issue by ttb-inc** [xclud/web3dart#87]
Hi
I have a package compatibility issue.

```
Because web3dart >=2.5.2 depends on stream_channel ^2.1.1 and every version of flutter_test from sdk depends on stream_channel 2.1.0, web3dart >=2.5.2 is incompatible with flutter_test from sdk.
And because firebase_core_platform_interface >=4.4.3 depends on flutter_test from sdk, web3dart >=2.5.2 is incompatible with firebase_core_platform_interface >=4.4.3.
And because every version of ttb_core from path depends on firebase_crashlytics 3.0.10 which depends on firebase_core_platform_interface ^4.5.2, web3dart >=2.5.2 is incompatible with ttb_core from path.
So, because ttb_wallet depends on both ttb_core from path and web3dart 2.6.1, version solving failed.
pub finished with exit code 1
```

What's a good way to solve this problem?

Method 1. Use a lower version of web3dart.
Method 2. Use a lower version of firebase.
Method 3. Use another method. (Please let me know)

This issue will be closed in time.
Thanks.

**Comment by gizemgizg** [comment]
same problem. I solved it using dependency_overrides @ttb-inc 
dependency_overrides:
   stream_channel: ^2.1.0
   async: ^2.9.0

**Comment by ttb-inc** [comment]
> same problem. I solved it using dependency_overrides @ttb-inc dependency_overrides: stream_channel: ^2.1.0 async: ^2.9.0

There are warnings, but Functional tests also seem to have no problems.
Thank you very much.
