### ISSUE TITLE
export length_tracking_byte_sink.dart

### ISSUE THREAD

**Issue by developerpaaji** [xclud/web3dart#96]
In order to deploy contract we need 'length_tracking_byte_sink.dart' to encode abi data. Currently its not exported from web3.dart

**Comment by xclud** [comment]
Can you share/describe the way you are deploying your contract?

**Comment by developerpaaji** [comment]
Here is the code
`  List<int> data = [];
   // this is basically Channel.bin
    data.addAll(hexToBytes(contractBinCode));
    AbiType abiType = parseAbiType('(address)');
    final sink = LengthTrackingByteSink();
   // Adding arguments
    abiType.encode(
        [EthereumAddress.fromHex(marketplaceAddress)], sink);
    data.addAll(sink.asBytes());
    final transaction = Transaction(
      to: null,
      from: walletService.credentials!.address,
      data: Uint8List.fromList(data),
    );
    final transactionHash = await web3Client.sendTransaction(
        walletService.credentials!, transaction,
        chainId: 80001);
`

**Comment by xclud** [comment]
I will fix this issue with the next release.

Meanwhile, use this code:

```
import 'package:web3dart/src/utils/length_tracking_byte_sink.dart';
```

Closing this one but please feel free to open a new issue anytime.

**Comment by developerpaaji** [comment]
Yeah i am using this way if you want i can create pull request and you can accept it

**Comment by xclud** [comment]
Please do :)

**Comment by xclud** [comment]
Please make a `part`.

**Comment by developerpaaji** [comment]
oh okay

**Comment by developerpaaji** [comment]
created
